services:

  waf:
    image: docker.io/library/haproxy:lts-alpine
    volumes:
      - ./waf:/usr/local/etc/haproxy:ro
    ports:
      - 22022:8080
      - 8150:9090
    depends_on:
      web:
        condition: service_started

  web:
    platform: linux/amd64
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8200:80
    depends_on:
      tier1:
        condition: service_healthy
      otel-collector:
        condition: service_started

  tier1:
    build:
      context: ./tier1-python
      dockerfile: Dockerfile
    image: tier1-python:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports: 
      - 8300:8080
    depends_on:
      tier2:
        condition: service_started
      queue:
        condition: service_healthy
      db:
        condition: service_healthy

  tier2:
    build:
      context: ./tier2-nodejs
      dockerfile: Dockerfile
    image: tier2-nodejs:latest
    ports:
      - 8400:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/library/mysql:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 8500:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  queue:
    image: docker.io/library/rabbitmq:3-management
    ports:
      - 8600:15672
      - 8650:5672
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics" ,"-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  queue_consumer:
    build:
      context: ./consumer-java
      dockerfile: Dockerfile
    depends_on:
      queue:
        condition: service_healthy
      db:
        condition: service_healthy
